[package]
name = "lunatic-sys"
version = "0.13.0"
edition = "2021"
description = "Exported guest functions for the Lunatic VM"
license = "Apache-2.0/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
